# -*- coding: utf-8 -*-
"""KOMAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bywJOeimbEUvgE6oHFDSEYU-1G5yAZWj

## INSTAL NECESSARY LIBRARIES
"""

!pip install ultralytics
import ultralytics
ultralytics.checks()

!mkdir logo   #USED TO CREATE A FOLDER

!ls   # USED TO CHECK

path='/content/logo'

import os

# Commented out IPython magic to ensure Python compatibility.
os.chdir('/content/logo')
# %pwd

"""# WE CAN TAKE DATASET BY THREE METHODS :-
## 1.DIRECT FROM ROBOFLOW
## 2.BY DRIVE
## 3.BY UPLOADING ZIP FILE

## **ROBOFLOW DATASET**
"""

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="Ar89hNDRHJJIHgYY6HqA")      #this api is not visible at the time you copy code from roboflow
project = rf.workspace("testspace-6ia9d").project("logo-detection-wrdch")   #this is visible when u paste it in google colab
version = project.version(1)
dataset = version.download("yolov8")

"""### **TRAIN MODEL WITH 10 EPOCH**
for training model use T4-GPU
"""

from ultralytics import YOLO

# Load a base model (you can also try yolov8m.pt or yolov8n.pt)
model = YOLO('yolov8s.pt')

# Train the model
model.train(
    data='/content/logo/logo-detection-1/data.yaml',
    epochs=10,
    imgsz=640
)



import shutil                          #THIS COMMAND IS USED TO REMOVE FOLDER
shutil.rmtree('/content/runs')    #os.remove IS USED TO REMOVE FILES

# Load trained model
model = YOLO('/content/logo/runs/detect/train/weights/best.pt')

# Run detection on train images
results = model.predict(                                         #TRAIN IMAGES
    source='/content/logo/logo-detection-1/train/images',
    save=True,
    conf=0.25
)

from IPython.display import Image, display
import glob

# Show first 5 predicted images                            #TRAIN IMAGES OUTPUT
for image_path in glob.glob('/content/logo/runs/detect/predict/*.jpg')[:5]:
    display(Image(filename=image_path))

from google.colab import drive        #used to connect drive with googlecolab
drive.mount('/content/drive')

# Copy the folder to your Google Drive              #used to move file from any location to any location
!cp -r /content/logo/yolov8s.pt  /content/drive/MyDrive/logo/

# Load the trained model
from ultralytics import YOLO

model = YOLO('/content/logo/runs/detect/train/weights/best.pt')

# Run detection on test images                                               #TEST IMAGES
results = model.predict(
    source='/content/logo/logo-detection-1/test/images',
    save=True,
    conf=0.25  # confidence threshold
)

from IPython.display import Image, display
import glob

# Display the first 5 predicted test images
for img_path in glob.glob('/content/logo/runs/detect/predict1*/' + '*.jpg')[:5]: #TEST IMAGES OUTPUT
    display(Image(filename=img_path))

from ultralytics import YOLO

# Load the trained model
model = YOLO('//content/logo/runs/detect/train/weights/best.pt')

# Predict on validation images                                   #VALID IMAGES
model.predict(
    source='/content/logo/logo-detection-1/valid/images',
    save=True,
    conf=0.25,
    imgsz=640
)

from IPython.display import Image, display
import glob
                                                                              #  VALID IMAGES OUTPUT
# Display a few predicted validation images
for img_path in glob.glob('/content/logo/runs/detect/predict2/*.jpg')[:9]:
    display(Image(filename=img_path))

import shutil
shutil.make_archieve